export const homeObjOne = {
  lightBg: false,
  primary: true,
  imgStart: "",
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "MY company",
  headLine: "Lead Generation ",
  description: "We Help bussiness ",
  buttonLabel: "Get Started",
  img: require("../../images/1.png"),
  alt: "Image",
  start: "",
};
export const homeObjTwo = {
  lightBg: true,
  primary: false,
  imgStart: "start",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "MY company",
  headLine: "Lead Generation ",
  description: "We Help bussiness ",
  buttonLabel: "Get Started",
  img: require("../../images/2.png"),
  alt: "Image",
  start: "true",
};

export const homeObjThree = {
  lightBg: false,
  primary: true,
  imgStart: "",
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "MY company",
  headLine: "Lead Generation ",
  description: "We Help bussiness ",
  buttonLabel: "Get Started",
  img: require("../../images/1.png"),
  alt: "Image",
  start: "",
};
export const homeObjFour = {
  lightBg: true,
  primary: false,
  imgStart: "start",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "MY company",
  headLine: "Lead Generation ",
  description: "We Help bussiness ",
  buttonLabel: "Get Started",
  img: require("../../images/2.png"),
  alt: "Image",
  start: "true",
};
