export const introObj = {
  id: "about",
  lightBg: false,
  primary: true,
  imgStart: "",
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "嗨 你好",
  headLine: "我是羅文駿",
  description:
    "「程式導師實驗計劃第四期」的學生，結束後，對於自己的不足於是利用 codecademy pro 自學，加深自己對前後端的知識。接觸網頁前後端對 coding 的熱愛，享受把問題解出來的霎那間的成就感，讓自己的想法實踐於 code 上，目前正在不斷學習與精進努力朝著前端工程師前進。",
  buttonLabel: "Get Started",
  img: "http://www.urad.com.tw/wp-content/uploads/2015/08/giphy.gif",
  alt: "Image",
  start: "",
};
export const projectObj = {
  id: "projects",
  lightBg: true,
  primary: false,
  imgStart: "start",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headLine: "我的作品",
  description: "We Help bussiness ",
  buttonLabel: "Get Started",
  img: require("../../images/2.png"),
  alt: "Image",
  start: "true",
};

export const educationData = [
  {
    targetId: "education",
    id: "experience",
    lightBg: false,
    primary: true,
    imgStart: "",
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true,
    topLine: "Education",
    headLine: "LIDEMY 第四期的程式導師計畫",
    description: "畢業生",
    time: "Jun, 2020 – Jan, 2021",
    content:
      "參加由 Lidemy 鋰學院創辦人 Huli 所開設的 【 程式導師計畫第四期 】，過著與 24 週作業 為伍的日子，期間加強許多關於網頁前後端的觀念。",
  },
  {
    id: "experience1",
    lightBg: false,
    primary: true,
    imgStart: "",
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true,
    topLine: "",
    headLine: "淡江大學",
    description: "學士 西班牙語文學系 / 經濟學系",
    time: "Sep, 2010 – Jun, 2015",
    content:""
    },
];
export const experienceData = [
  {
    targetId: "experience",
    id: "experience",
    lightBg: true,
    primary: false,
    imgStart: "start",
    lightTopLine: false,
    lightText: false,
    lightTextDesc: false,
    topLine: "Work Experience",
    headLine: "奇方動力有限公司",
    description: "行銷助理",
    time: "Jan, 2019 – Mar, 2020",
    content: "與設計部門合作發想文案撰寫，以及簡易的數據分析",
  },
  {
    id: "experience",
    lightBg: true,
    primary: false,
    imgStart: "start",
    lightTopLine: false,
    lightText: false,
    lightTextDesc: false,
    topLine: "Work Experience",
    headLine: "東吳大學",
    description: "研究助理",
    time: "Nov, 2015 – Feb, 2018",
    content: "協助研究計畫的進行，處理相關行政工作。",
  },
];
